name: arena
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python==3.10.6
  - plotly==5.10.0
  - pytorch==1.14
  - numpy==1.23.4
  - ipywidgets==7.7.2
  - pytest==7.1.3
  - pandas==1.5.0
  - torchvision==0.13.1
  - tqdm==4.64.1
  - transformers==4.24.0
  - pip: 
    - einops==0.5.0
    - fancy-einsum==0.0.3