FROM continuumio/miniconda3

# Create the environment:
COPY environment.yml .
RUN conda env create -f environment.yml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "arena", "/bin/bash", "-c"]

# Activate the environment, and make sure it's activated:
RUN echo "Make sure flask is installed:"
RUN python -c "import flask"

COPY app /app
COPY models /models
COPY data /data
ENV NREPEATS=7

ENV PATH /opt/conda/envs/arena/bin:$PATH
# CMD ["bash", "-c", "source activate arena && python app/app.py"]

CMD ["bash", "-c", "source activate arena && python app/gradio_test.py"]