wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1667993171.597207
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.6
      5: 0.13.4
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 256
device:
  desc: null
  value: cpu
dropout:
  desc: null
  value: 0.1
hidden_size:
  desc: null
  value: 64
layer_norm_epsilon:
  desc: null
  value: 1.0e-05
lr:
  desc: null
  value: 0.00125
num_epochs:
  desc: null
  value: 10
num_heads:
  desc: null
  value: 4
num_layers:
  desc: null
  value: 2
seq_len:
  desc: null
  value: 6
test_set_size:
  desc: null
  value: 1000
train_set_size:
  desc: null
  value: 100000
vocab_size:
  desc: null
  value: 10
